In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import os
os.listdir('/content/drive/MyDrive/AmazonML2026')

['dataset.zip']

In [10]:
!unzip /content/drive/MyDrive/AmazonML2026/dataset.zip

Archive:  /content/drive/MyDrive/AmazonML2026/dataset.zip
   creating: student_resource/
  inflating: __MACOSX/._student_resource
  inflating: student_resource/Documentation_template.md
  inflating: __MACOSX/student_resource/._Documentation_template.md
  inflating: student_resource/.DS_Store
  inflating: __MACOSX/student_resource/._.DS_Store
   creating: student_resource/dataset/
  inflating: __MACOSX/student_resource/._dataset
   creating: student_resource/utils/
  inflating: __MACOSX/student_resource/._utils
  inflating: student_resource/README.md
  inflating: __MACOSX/student_resource/._README.md
  inflating: student_resource/dataset/.DS_Store
  inflating: __MACOSX/student_resource/dataset/._.DS_Store
   creating: student_resource/dataset/test/
  inflating: __MACOSX/student_resource/dataset/._test
   creating: student_resource/dataset/train/
  inflating: __MACOSX/student_resource/dataset/._train
  inflating: student_resource/utils/validate_submission.py
  inflating: __MACOSX/student_resource/utils/._validate_submission.py
  inflating: student_resource/dataset/test/test_source2.tsv
  inflating: __MACOSX/student_resource/dataset/test/._test_source2.tsv
  inflating: student_resource/dataset/test/test_source3.tsv
  inflating: __MACOSX/student_resource/dataset/test/._test_source3.tsv
  inflating: student_resource/dataset/test/test_source1.tsv
  inflating: __MACOSX/student_resource/dataset/test/._test_source1.tsv
  inflating: student_resource/dataset/train/train_ground_truth.tsv
  inflating: __MACOSX/student_resource/dataset/train/._train_ground_truth.tsv
  inflating: student_resource/dataset/train/train_source2.tsv
  inflating: __MACOSX/student_resource/dataset/train/._train_source2.tsv
  inflating: student_resource/dataset/train/train_source3.tsv
  inflating: __MACOSX/student_resource/dataset/train/._train_source3.tsv
  inflating: student_resource/dataset/train/train_source1.tsv
  inflating: __MACOSX/student_resource/dataset/train/._train_source1.tsv

In [23]:
import os
print(os.listdir('./student_resource/dataset/train'))

['train_ground_truth.tsv', 'train_source3.tsv', 'train_source2.tsv', 'train_source1.tsv']

In [24]:
!mv student_resource /content/drive/MyDrive/AmazonML2026/resources

In [63]:
import numpy as np
import pandas as pd

pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

from google.colab import data_table
data_table.enable_dataframe_formatter()

PWD = "/content/drive/MyDrive/AmazonML2026/resources"

In [30]:
df1 = pd.read_csv((PWD+"/dataset/train/train_source1.tsv"), sep="\t")

In [31]:
df2 = pd.read_csv((PWD+"/dataset/train/train_source2.tsv"), sep="\t")

In [32]:
df3 = pd.read_csv((PWD+"/dataset/train/train_source3.tsv"), sep="\t")

In [33]:
dft = pd.read_csv((PWD+"/dataset/train/train_ground_truth.tsv"), sep="\t")

In [64]:
print(df1.info(), df2.info(), df3.info(), dft.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         object
 1   business_name     object
 2   business_address  object
 3   country           object
dtypes: object(4)
memory usage: 67.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5034616 entries, 0 to 5034615
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         object
 1   business_name     object
 2   business_address  object
 3   country           object
dtypes: object(4)
memory usage: 153.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         object
 1   business_name     object
 2   business_address  object
 3   country           object
dtypes: object(4)
memory usage: 161.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 2 columns):
 #   Column              Dtype
---  ------              -----
 0   source1_entity_id   object
 1   matched_entity_ids  object
dtypes: object(2)
memory usage: 33.7+ MB
None None None None

In [65]:
df1.iloc[0]

entity_id                                     S1-925783039
business_name                          Orelee's Barbershop
business_address    1795 Westchester Drive, High Point, NC
country                                                 US
Name: 0, dtype: object

In [66]:
dft.iloc[0]

source1_entity_id                                                           S1-965667
matched_entity_ids    S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
Name: 0, dtype: object

In [70]:
for i in range(5):
  print("============================= The company from source 1: ==============================================")
  print(df1.loc[df1['entity_id'] == dft.iloc[i]['source1_entity_id']])

  print("=============== The companies matching from 2 and 3: =================")
  id_list = dft.iloc[i]['matched_entity_ids'].split(',')
  for id in id_list:
    if not df2.loc[df2['entity_id'] == id].empty:
      print(df2.loc[df2['entity_id'] == id])
    if not df3.loc[df3['entity_id'] == id].empty:
      print(df3.loc[df3['entity_id'] == id])

============================= The company from source 1: ==============================================
         entity_id                 business_name                  business_address country
1286323  S1-965667  Maure Williams Colombier Inc  85 Wayne Avenue, Ticonderoga, NY      US
=============== The companies matching from 2 and 3: =================
            entity_id                 business_name business_address country
1376739  S2-681193310  Maure Wilblims Colombier Inc              NaN      US
            entity_id             business_name business_address country
2003754  S2-743505751  Maure Williams Colombier              NaN      US
            entity_id business_name                                  business_address country
1217885  S3-775321672       Dréxkor  85 Wanye Avenue, Ticonderoga Townshiip, New York      US
           entity_id               business_name                            business_address country
5223525  S3-11291185  maurewilliamscolombier.com  Wayne Ave, Ticonderoga Townshiip, New York      US
          entity_id              business_name business_address country
63830  S3-860443364  Maure Williams Inc Center              NaN      US
============================= The company from source 1: ==============================================
           entity_id        business_name                                                   business_address country
1898165  S1-55344266  Raj Investments LLP  6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu   India
=============== The companies matching from 2 and 3: =================
            entity_id                    business_name                                                   business_address country
4130950  S2-249013014  ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி  6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu   India
            entity_id        business_name                                                   business_address country
1886844  S2-197070651  Raj Investments LLP  6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu   India
            entity_id             business_name                                           business_address country
1348219  S3-478195123  Raj Investments எல்எல்பி  6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, TN   India
           entity_id                    business_name                                                  business_address country
805792  S3-384364074  ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி  6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, தமிழ்நாடு   India
============================= The company from source 1: ==============================================
           entity_id                         business_name                   business_address country
547338  S1-343815751  Dahlia Power Reliable Scientific LLC  630 45th Terrace, Kansas City, MO      US
=============== The companies matching from 2 and 3: =================
            entity_id          business_name                         business_address country
3579917  S2-790675320  Dahlia Power Reliable  KANSAS CITY, MO, 630 45ND TERRACE, null      US
            entity_id                     business_name                     business_address country
1901972  S2-479876582  Dahlia Power Reliable Scientific  45ND TERRACE, null, KANSAS CITY, MO      US
            entity_id                        business_name                         business_address country
5012680  S3-878454467  Dahlia Ponr Reliable Scientific LLC  Missouri, 630 45th Terrace, Kansas City      US
============================= The company from source 1: ==============================================
            entity_id            business_name                                                                              business_address country
1072115  S1-656753428  Ss Food Private Limited  Af-684, Nandgram Near Mother India Public School. Ph. 989, 9487203, Ghaziabad, Uttar Pradesh   India
=============== The companies matching from 2 and 3: =================
            entity_id              business_name                                                                              business_address country
2630198  S2-153058913  एसएस फूड प्राइवेट लिमिटेड  AF-0684, NANDGRAM NEAR MOTHER INDIA PUBLIC SCHOOL. PH. 989, GHAZIABAD, 9487203, उत्तर प्रदेश   India
           entity_id              business_name                            business_address country
5014138  S2-24659151  एसएस फूड प्राइवेट लिमिटेड  AF-0684, Uttar Pradesh, GHAZIABAD, 9487203   India
            entity_id              business_name       business_address country
4602558  S3-679606215  एसएस फूड प्राइवेट लिमिटेड  Af-684, Ghaziabad, UP   India
============================= The company from source 1: ==============================================
           entity_id      business_name                 business_address country
539414  S1-102811957  Payne Enterprises  3315 Fremont Street, Peoria, IL      US
=============== The companies matching from 2 and 3: =================
           entity_id      business_name             business_address country
731099  S2-478959098  Payne Énterprises  3315 FREMONT ST, PEORIA, IL      US
            entity_id     business_name             business_address country
1776076  S2-553508714  Payne Enterpires  3315 FREMONT ST, PEORIA, IL      US
           entity_id      business_name                business_address country
385243  S2-625774905  PAYNE-ENRTPRMISES  3315 FREMONT SAINT, PEORIA, IL      US
           entity_id      business_name                   business_address country
876298  S3-728090388  Payne Etrepndiels  3315 Fremont St, Peoria, Illinois      US
            entity_id      business_name                       business_address country
4587222  S3-928796641  Payne Énterprises  3315 Fremont Street, Peoria, Illinois      US
           entity_id           business_name              business_address country
666012  S3-449308785  Payne Enterprises  LLC  Fremont St, Peoria, Illinois      US